const keywords = [
    'Bếp UIT',
    'bep UIT',
    'bep UIT',
    'Bếp UIT',
    'BẾPUIT',
    'BẾpUIT',
    'BẾPuit',
    'bếpuit',
    'bếpUIT',
    'bepUIT',
    'bepUIT',
    'Bếp UTI',
    'BẾP UTI',
    'BẾp UTI',
    'BẾP uti',
    'bếp uti',
    'bếp UTI',
    'bep UTI',
    'bep UTI',
    'Bếp UTI',
    'BẾPUTI',
    'BẾpUTI',
    'BẾPuti',
    'bếputi',
    'bếpUTI',
    'bepUTI',
    'bepUTI',
    'beep UIT',
    'Bêps UIT',
    'beps uit',
    'bpe uit',
    'bpees uit',
    'bpế uit',
    'Bếp UTI',
    'BẾP UTI',
    'BẾp UTI',
    'BẾP uti',
    'bếp uti',
    'bếp UTI',
    'bep UTI',
    'bep UTI',
    'Bếp UTI',
    'BẾPUTI',
    'BẾpUTI',
    'BẾPuti',
    'bếputi',
    'bếpUTI',
    'bepUTI',
    'bepUTI',
    'beep UIT',
    'Bêps UIT',
    'beps uit',
    'bpe uit',
    'bpees uit',
    'bpế uit',
    'Bếp UTI',
    'BẾP UTI',
    'BẾp UTI',
    'BẾP uti',
    'bếp uti',
    'bếp UTI',
    'bep UTI',
    'bep UTI',
    'Bếp UTI',
    'BẾPUTI',
    'BẾpUTI',
    'BẾPuti',
    'bếputi',
    'bếpUTI',
    'bepUTI',
    'bepUTI',
    'beep UIT',
    'Bêps UIT',
    'beps uit',
    'bpe uit',
    'bpees uit',
    'bpế uit',
    '4food',
    '4Food',
    '4FOOD',
    '4fod',
    '4Fod',
    '4FOD',
    '4food restaurant',
    '4Food restaurant',
    '4FOOD restaurant',
    'chuẩn 4food',
    'chuẩn 4Food',
    'chuan 4Food',
    'nhà hàng chuẩn 4food',
    'nhà hàng chuẩn 4Food',
    'nhà hàng 4Food',
    'nhà hàng 4food',
    'nhà hàng gần đây',
    'nhà hàng 4food gần đây',
    'nhà hàng 4Food gần đây',
    'nha hang 4food',
    'nha hang 4Food',
    'nhà hàng 4Food sài gòn',
    'Nhà hàng 4Food HCM',
    '4Food restaurant Hồ Chí Minh',
    'Nhà hàng 4Food Sài Gòn',
    'Nhà hàng 4Food TP.HCM',
    'NHÀ HÀNG 4FOOD TP.HCM',
    'nhà hàng 4food tp.hcm',
    'Nhà hàng 4Food TP HCM',
    'NHÀ HÀNG 4FOOD TP HCM',
    'nhà hàng 4food tp hcm',
    'Nha hang 4Food TP.HCM',
    'NHA HANG 4FOOD TP.HCM',
    'nha hang 4food tp.hcm',
    'Nhà hàng 4Food TP.HCM',
    'NHÀ HÀNG 4FOOD TP.HCM',
    'nhà hàng 4food tp.hcm',
    '4Food Sài Gòn',
    '4FOOD SÀI GÒN',
    '4food sài gòn',
    '4Food Sai Gon',
    '4FOOD SAI GON',
    '4food sai gon',
    '4Food Saigon',
    '4FOOD SAIGON',
    '4food saigon',
    '4Food Sài Gòn',
    '4FOOD SÀI GÒN',
    '4food sài gòn',
    '4Food gần đây',
    '4FOOD GẦN ĐÂY',
    '4food gần đây',
    '4Food gan day',
    '4FOOD GAN DAY',
    '4food gan day',
    '4Food gần đây',
    '4FOOD GẦN ĐÂY',
    '4food gần đây',
    'bếp UIT restaurant',
    'Bếp UIT restaurant',
    'BẾP UIT restaurant',
    'nhà hàng Bếp UIT',
    'nhà hàng bếp UIT',
    'nhà hàng gần đây',
    'nhà hàng bếp UIT gần đây',
    'nhà hàng Bếp UIT gần đây',
    'nha hang bếp UIT',
    'nha hang Bếp UIT',
    'nhà hàng Bếp UIT sài gòn',
    'Nhà hàng Bếp UIT HCM',
    'Bếp UIT restaurant Hồ Chí Minh',
    'Nhà hàng Bếp UIT Sài Gòn',
    'Nhà hàng Bếp UIT TP.HCM',
    'NHÀ HÀNG BẾP UIT TP.HCM',
    'nhà hàng bếp UIT tp.hcm',
    'Nhà hàng Bếp UIT TP HCM',
    'NHÀ HÀNG BẾP UIT TP HCM',
    'nhà hàng bếp UIT tp hcm',
    'Nha hang Bếp UIT TP.HCM',
    'NHA HANG BẾP UIT TP.HCM',
    'nha hang bếp UIT tp.hcm',
    'Nhà hàng Bếp UIT TP.HCM',
    'NHÀ HÀNG BẾP UIT TP.HCM',
    'nhà hàng bếp UIT tp.hcm',
    'Bếp UIT Sài Gòn',
    'BẾP UIT SÀI GÒN',
    'bếp uit sài gòn',
    'Bếp UIT Sai Gon',
    'BẾP UIT SAI GON',
    'bếp uit sai gon',
    'Bếp UIT Saigon',
    'BẾP UIT SAIGON',
    'bếp uit saigon',
    'Bếp UIT Sài Gòn',
    'BẾP UIT SÀI GÒN',
    'bếp uit sài gòn',
    'Bếp UIT gần đây',
    'BẾP UIT GẦN ĐÂY',
    'bếp uit gần đây',
    'Bếp UIT gan day',
    'BẾP UIT GAN DAY',
    'bếp uit gan day',
    'Bếp UIT gần đây',
    'BẾP UIT GẦN ĐÂY',
    'bếp uit gần đây',
]

export default keywords
