const keywords = [
    'Bếp UIT',
    'bep UIT',
    'bep UIT',
    'Bếp UIT',
    'BẾPUIT',
    'BẾpUIT',
    'BẾPuit',
    'bếpuit',
    'bếpUIT',
    'bepUIT',
    'bepUIT',
    'Bếp UTI',
    'BẾP UTI',
    'BẾp UTI',
    'BẾP uti',
    'bếp uti',
    'bếp UTI',
    'bep UTI',
    'bep UTI',
    'Bếp UTI',
    'BẾPUTI',
    'BẾpUTI',
    'BẾPuti',
    'bếputi',
    'bếpUTI',
    'bepUTI',
    'bepUTI',
    'beep UIT',
    'Bêps UIT',
    'beps uit',
    'bpe uit',
    'bpees uit',
    'bpế uit',
    'Bếp UTI',
    'BẾP UTI',
    'BẾp UTI',
    'BẾP uti',
    'bếp uti',
    'bếp UTI',
    'bep UTI',
    'bep UTI',
    'Bếp UTI',
    'BẾPUTI',
    'BẾpUTI',
    'BẾPuti',
    'bếputi',
    'bếpUTI',
    'bepUTI',
    'bepUTI',
    'beep UIT',
    'Bêps UIT',
    'beps uit',
    'bpe uit',
    'bpees uit',
    'bpế uit',
    'Bếp UTI',
    'BẾP UTI',
    'BẾp UTI',
    'BẾP uti',
    'bếp uti',
    'bếp UTI',
    'bep UTI',
    'bep UTI',
    'Bếp UTI',
    'BẾPUTI',
    'BẾpUTI',
    'BẾPuti',
    'bếputi',
    'bếpUTI',
    'bepUTI',
    'bepUTI',
    'beep UIT',
    'Bêps UIT',
    'beps uit',
    'bpe uit',
    'bpees uit',
    'bpế uit',
    'Nhà hàng bếp uit',
    'Nhà hàng bếp UIT',
    'nha hang bep uit',
    'Chuẩn 4food',
    '4food',
    'let us cook',
    'Let us cook',
]

export default keywords
